Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "install.sh"

  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      node.vm.box = "centos/7"
      node.vm.network "private_network", ip: "192.168.24.3#{i}"
#      node.vm.provision "shell", path: "install.sh", privileged: true
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node-#{i}"
        vb.gui = false
        vb.memory = "512"
      end
    
    end

  end
  
end
